
<?php

// Vai sair com o SQL
$_SESSION['produtos'] = [
    1 => [
        'id' => 1,
        'nome' => 'Camisa CODIFICA+',
        'sku' => '123456',
        'unidade_medida_id' => '1',
        'valor' => 1500.00,
        'quantidade' => 1,
        'categoria_id' => '5',
    ],
    [
        'id' => 2,
        'nome' => 'Geladeira',
        'sku' => '654321',
        'unidade_medida_id' => '1',
        'valor' => 2500.00,
        'quantidade' => 5,
        'categoria_id' => '2',
    ],
    [
        'id' => 3,
        'nome' => 'Televisão',
        'sku' => '112233',
        'unidade_medida_id' => '1',
        'valor' => 1800.00,
        'quantidade' => 7,
        'categoria_id' => '1',
    ],
    [
        'id' => 4,
        'nome' => 'Sofá',
        'sku' => '445566',
        'unidade_medida_id' => '1',
        'valor' => 1200.00,
        'quantidade' => 3,
        'categoria_id' => '3',
    ],
    [
        'id' => 5,
        'nome' => 'Mesa de Jantar',
        'sku' => '778899',
        'unidade_medida_id' => '1',
        'valor' => 800.00,
        'quantidade' => 2,
        'categoria_id' => '3',
    ],
    [
        'id' => 6,
        'nome' => 'Cadeira',
        'sku' => '998877',
        'unidade_medida_id' => '1',
        'valor' => 150.00,
        'quantidade' => 12,
        'categoria_id' => '3',
    ],
    [
        'id' => 7,
        'nome' => 'Camiseta',
        'sku' => '334455',
        'unidade_medida_id' => '1',
        'valor' => 50.00,
        'quantidade' => 20,
        'categoria_id' => '5',
    ],
    [
        'id' => 8,
        'nome' => 'Jeans',
        'sku' => '665544',
        'unidade_medida_id' => '1',
        'valor' => 120.00,
        'quantidade' => 15,
        'categoria_id' => '5',
    ],
    [
        'id' => 9,
        'nome' => 'Micro-ondas',
        'sku' => '889900',
        'unidade_medida_id' => '1',
        'valor' => 350.00,
        'quantidade' => 8,
        'categoria_id' => '2',
    ],
    [
        'id' => 10,
        'nome' => 'Liquidificador',
        'sku' => '776655',
        'unidade_medida_id' => '1',
        'valor' => 120.00,
        'quantidade' => 10,
        'categoria_id' => '2',
    ],
    [
        'id' => 11,
        'nome' => 'Quadro Decorativo',
        'sku' => '443322',
        'unidade_medida_id' => '1',
        'valor' => 200.00,
        'quantidade' => 5,
        'categoria_id' => '4',
    ],
    [
        'id' => 12,
        'nome' => 'Luminária',
        'sku' => '556677',
        'unidade_medida_id' => '1',
        'valor' => 80.00,
        'quantidade' => 10,
        'categoria_id' => '4',
    ],
    [
        'id' => 13,
        'nome' => 'Tapete',
        'sku' => '990011',
        'unidade_medida_id' => '8',
        'valor' => 350.00,
        'quantidade' => 7,
        'categoria_id' => '4',
    ],
    [
        'id' => 14,
        'nome' => 'Aspirador de Pó',
        'sku' => '554433',
        'unidade_medida_id' => '1',
        'valor' => 400.00,
        'quantidade' => 4,
        'categoria_id' => '2',
    ],
    [
        'id' => 15,
        'nome' => 'Impressora',
        'sku' => '223344',
        'unidade_medida_id' => '1',
        'valor' => 600.00,
        'quantidade' => 6,
        'categoria_id' => '1',
    ],
    [
        'id' => 16,
        'nome' => 'Cama de Casal',
        'sku' => '887766',
        'unidade_medida_id' => '1',
        'valor' => 2200.00,
        'quantidade' => 2,
        'categoria_id' => '3',
    ],
    [
        'id' => 17,
        'nome' => 'Colchão',
        'sku' => '009988',
        'unidade_medida_id' => '1',
        'valor' => 1200.00,
        'quantidade' => 3,
        'categoria_id' => '3',
    ],
    [
        'id' => 18,
        'nome' => 'Blusa de Moletom',
        'sku' => '667788',
        'unidade_medida_id' => '1',
        'valor' => 90.00,
        'quantidade' => 18,
        'categoria_id' => '5',
    ],
    [
        'id' => 19,
        'nome' => 'Vestido',
        'sku' => '331122',
        'unidade_medida_id' => '1',
        'valor' => 150.00,
        'quantidade' => 12,
        'categoria_id' => '5',
    ],
    [
        'id' => 20,
        'nome' => 'Sapato',
        'sku' => '776600',
        'unidade_medida_id' => '1',
        'valor' => 200.00,
        'quantidade' => 10,
        'categoria_id' => '5',
    ],
    [
        'id' => 21,
        'nome' => 'Relógio de Pulso',
        'sku' => '445599',
        'unidade_medida_id' => '1',
        'valor' => 300.00,
        'quantidade' => 9,
        'categoria_id' => '1',
    ],
    [
        'id' => 22,
        'nome' => 'Smartwatch',
        'sku' => '990044',
        'unidade_medida_id' => '1',
        'valor' => 900.00,
        'quantidade' => 6,
        'categoria_id' => '1',
    ],
    [
        'id' => 23,
        'nome' => 'Fogão',
        'sku' => '112211',
        'unidade_medida_id' => '1',
        'valor' => 1200.00,
        'quantidade' => 4,
        'categoria_id' => '2',
    ],
    [
        'id' => 24,
        'nome' => 'Forno Elétrico',
        'sku' => '668899',
        'unidade_medida_id' => '1',
        'valor' => 800.00,
        'quantidade' => 5,
        'categoria_id' => '2',
    ],
    [
        'id' => 25,
        'nome' => 'Cortina',
        'sku' => '223355',
        'unidade_medida_id' => '1',
        'valor' => 150.00,
        'quantidade' => 8,
        'categoria_id' => '4',
    ],
    [
        'id' => 26,
        'nome' => 'Ventilador',
        'sku' => '776688',
        'unidade_medida_id' => '1',
        'valor' => 200.00,
        'quantidade' => 9,
        'categoria_id' => '2',
    ],
    [
        'id' => 27,
        'nome' => 'Ar-condicionado',
        'sku' => '665522',
        'unidade_medida_id' => '1',
        'valor' => 2200.00,
        'quantidade' => 3,
        'categoria_id' => '2',
    ],
    [
        'id' => 28,
        'nome' => 'Gaveteiro',
        'sku' => '556611',
        'unidade_medida_id' => '1',
        'valor' => 350.00,
        'quantidade' => 7,
        'categoria_id' => '3',
    ],
    [
        'id' => 29,
        'nome' => 'Estante',
        'sku' => '331188',
        'unidade_medida_id' => '1',
        'valor' => 500.00,
        'quantidade' => 5,
        'categoria_id' => '3',
    ],
    [
        'id' => 30,
        'nome' => 'Roupão de Banho',
        'sku' => '887722',
        'unidade_medida_id' => '1',
        'valor' => 180.00,
        'quantidade' => 8,
        'categoria_id' => '5',
    ],
];
